import { useState } from 'react';
import { NavLink, Outlet, useLocation } from 'react-router-dom';
import { Home, LockKeyhole, LogOut, ShieldCheck, UserRound } from 'lucide-react';
import { useAuth } from '../../lib/auth';
import content from '../../lib/content/inicio';
import { canAccess, planNames, plansWith } from '../../lib/plans';
import Icon from '../ui/Icon';
import { Badge, Button, EmptyState, Modal } from '../ui';
import { PodcastProvider, PersistentPlayer } from '../video/PodcastPlayer';
export function UrgentHelp({onClose}){return <Modal title="Busca acompañamiento ahora" onClose={onClose}><p>Si estás en peligro inmediato o necesitas atención urgente, comunícate con emergencias o acude al servicio de urgencias más cercano.</p><Button href="tel:123">Llamar al 123 · Colombia</Button><p>También puedes contactar a alguien de confianza para que te acompañe. Este foro y los formularios no se revisan de forma inmediata.</p></Modal>;}
export function MemberTitle({eyebrow='TU ESPACIO DE BIENESTAR',title,accent,description}){return <div className="member-title"><Badge>{eyebrow}</Badge><h1>{title} <em>{accent}</em></h1>{description&&<p>{description}</p>}</div>;}
function PlanLocked({module,profile}){return <><MemberTitle eyebrow="NO INCLUIDO EN TU PLAN" title={module.name} accent=""/><EmptyState icon={LockKeyhole} title={`Este espacio no está incluido en el plan ${planNames[profile.plan]||profile.plan}`}>Está disponible en el plan {plansWith(module.id).join(' y ')}. Si quieres ampliar tu acompañamiento, escríbenos y te orientamos.</EmptyState><div className="center" style={{marginTop:25}}><Button to="/contacto?asunto=general" arrow>Hablar con el equipo</Button></div></>;}
export default function MemberLayout(){const {profile,signOut}=useAuth();const [help,setHelp]=useState(false);const {pathname}=useLocation();const current=content.modules.find(m=>pathname.split('/')[2]===m.id);const locked=current&&!canAccess(profile,current.id);return <PodcastProvider><div className="member-shell"><aside className="member-sidebar"><div className="member-greeting"><span className="icon-disc"><Icon name="Flower2" size={25}/></span><h3>Hola, {profile?.nombre?.split(' ')[0]||'bienvenida'}</h3><p>{profile?.rol==='admin'?'Equipo EndoIntegral':`Plan ${planNames[profile?.plan]||'EndoIntegral'}`}</p></div><nav aria-label="Tu espacio privado"><NavLink to="/app" end><Home size={17}/>Inicio</NavLink>{content.modules.map(m=>{const open=canAccess(profile,m.id);return <NavLink key={m.id} to={`/app/${m.id}`} className={open?undefined:'is-locked'} aria-label={open?undefined:`${m.name} (no incluido en tu plan)`}><Icon name={m.icon}/>{m.name}{!open&&<LockKeyhole size={13} aria-hidden="true" style={{marginLeft:'auto',opacity:.6}}/>}</NavLink>;})}<NavLink to="/app/cuenta"><UserRound size={17}/>Mi cuenta</NavLink>{profile?.rol==='admin'&&<NavLink to="/admin"><ShieldCheck size={17}/>Panel del equipo</NavLink>}<button onClick={signOut}><LogOut size={17}/>Cerrar sesión</button></nav></aside><div className="member-content">{locked?<PlanLocked module={current} profile={profile}/>:<Outlet/>}<PersistentPlayer/></div></div><button className="urgent-button" onClick={()=>setHelp(true)}><Icon name="Heart" size={15}/>Necesito ayuda ahora</button>{help&&<UrgentHelp onClose={()=>setHelp(false)}/>}</PodcastProvider>;}
