import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});
await page.waitForTimeout(3500);
await fs.mkdir('artifacts',{recursive:true});
await page.screenshot({path:'artifacts/home-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'artifacts/home-mobile.png',fullPage:true});
console.log(JSON.stringify({title:await page.title(),errors,canvas:await page.locator('canvas').count(),overflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)}));
await browser.close();
